# Generated by Django 2.2.11 on 2020-03-25 19:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
